version: '3.8'
services:
  backend:
    build: ./backend       
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: backend
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
    networks:
      - app-network

  frontend:
    build: .   
    ports:
      - "3000:80"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
